### ISSUE TITLE
Present the Working Groups on ipfs.io

### ISSUE THREAD

**Issue by daviddias** [ipfs/project#14]
WG are the entry points for focus area and a place to new contributors to be welcomed in. Right now it takes multiple layers to get to the Working Groups which transforms to someone having to learn the whole project first.

**Comment by daviddias** [comment]
@ipfs/working-group-captains what do you think?

**Comment by mikeal** [comment]
Yes!

**Comment by momack2** [comment]
Agreed! Maybe we should have a wider issue to update the ipfs.io site? I
think we have other introduction videos, guides, and community resources
that might be more informative and empowering than what we had 2 years ago
when this was launched.

**Comment by mikeal** [comment]
Yes! Let's make sure that there's a good entry point for each working group linked for each one. The entry point should:

* Explain what the working group does for those unfamiliar.
* Has at least one call to action that points to a specific place people can get involved.

Many working groups already have this in the README but this is a good chance to make sure they are up to date.

**Comment by daviddias** [comment]
@ipfs/wg-gui-team Is this something we can get help with or your recommendation in how to do it (i.e. separate page or front page)?

**Comment by olizilla** [comment]
Yep, we can take a look at this.

**Comment by meiqimichelle** [comment]
Right now, the ipfs.io page is more like a marketing page about our project, not necessarily meant for contributors. I'm not sure that's the right place for listing our working groups.  However, if we do, my recommendations are:

- This should be a subpage, perhaps called 'contribute' or something like that -- guide people who want to contribute to a page about how to do that.
- Duplicate as little content as possible from the READMEs, and send people to the READMEs for more information. We want to create as little surface area for content falling out of date as possible, as people update READMEs all the time, and will forget to circle back and update the website, too. Treat it more as an index and explainer for info that is mostly in our GitHub repos.

**Comment by daviddias** [comment]
I receive a countless number of emails, twitter dms and other ways that people find to contact me to ask how they can contribute to the project. I typically requires me to go back and forth a couple of rounds to understand their background and goals to then point at the right point. 

It would be great to have this page ready so that I have a uniform way to present the working groups, their core focus and how people can join the Working Groups conversation.

**Comment by momack2** [comment]
I’d imagine this lives within a “contribute” context so as not to overly
force our internal organization on folks who just want to be consumers. How
do we want this to be different from where we publish our team structures
on GitHub? I think we should ideally aim for a structure that is really
easy to update or requires minimal updating (aka linking in to team
structures) since our set of working groups change/grow every month or two
(and I don’t think we want to update the website that frequently).

**Comment by daviddias** [comment]
Started working on it at https://github.com/ipfs/website/pull/291

**Comment by daviddias** [comment]
@olizilla volunteered to take this on to the finish line 🏁 🏎 ❤️

**Comment by momack2** [comment]
I think this is done! http://127.0.0.1:8080/ipns/ipfs.io/team/
