### ISSUE TITLE
Epic: Land Q1 OKRs

### ISSUE THREAD

**Issue by daviddias** [ipfs/project#19]
parent of ipfs/team-mgmt#804, parent of ipfs/team-mgmt#793, parent of ipfs/team-mgmt#814, parent of ipfs/team-mgmt#808, parent of ipfs/team-mgmt#806, parent of ipfs/team-mgmt#803, parent of ipfs/team-mgmt#802, parent of ipfs/team-mgmt#800, parent of ipfs/team-mgmt#799, parent of ipfs/team-mgmt#794,

**Comment by daviddias** [comment]
parent of ipfs/team-mgmt#793, parent of ipfs/team-mgmt#814, parent of ipfs/team-mgmt#808, parent of ipfs/team-mgmt#806, parent of ipfs/team-mgmt#803, parent of ipfs/team-mgmt#802, parent of ipfs/team-mgmt#800, parent of ipfs/team-mgmt#799, parent of ipfs/team-mgmt#794,

**Comment by daviddias** [comment]
See the Epic at https://waffle.io/ipfs/project?epic=5c3dd3ef5e6fa703779ff554

**Comment by momack2** [comment]
Given Q1 is over and we're working on landing Q2 okrs, figure it's time to close this
